#!/usr/bin/env node

/**
 * extract-i18n.js
 *
 * Scans src/ for gettext() calls, extracts unique msgids,
 * looks up translations from Django djangojs.po, writes per-language
 * messages.po into locale/.
 *
 * Usage:
 *   node scripts/extract-i18n.js <path-to-django-locale>
 */

import { readFileSync, writeFileSync, mkdirSync, readdirSync, existsSync } from "node:fs"
import { join, dirname } from "node:path"
import { fileURLToPath } from "node:url"

const __dirname = dirname(fileURLToPath(import.meta.url))
const root = join(__dirname, "..")
const djangoLocalePath = process.argv[2]

if (!djangoLocalePath) {
    console.error("Usage: node scripts/extract-i18n.js <django-locale-dir>")
    process.exit(1)
}

const GETTEXT_RE = /gettext\s*\(\s*["']([^"']+)["']\s*\)/g

const msgids = new Set()

function scanDir(dir) {
    if (!existsSync(dir)) return
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
        const full = join(dir, entry.name)
        if (entry.isDirectory() && entry.name !== "node_modules" && !entry.name.startsWith(".")) {
            scanDir(full)
        } else if (entry.isFile() && (entry.name.endsWith(".ts") || entry.name.endsWith(".js"))) {
            const content = readFileSync(full, "utf8")
            let match
            while ((match = GETTEXT_RE.exec(content)) !== null) {
                msgids.add(match[1])
            }
        }
    }
}

console.log("Scanning src/ for gettext() calls...")
scanDir(join(root, "src"))
console.log(`Found ${msgids.size} unique msgids.\n`)

if (msgids.size === 0) {
    console.log("No gettext() calls found. Exiting.")
    process.exit(0)
}

const languages = readdirSync(djangoLocalePath, { withFileTypes: true })
    .filter((e) => e.isDirectory())
    .map((e) => e.name)

console.log(`Looking up translations in ${languages.length} languages...`)

let totalTranslated = 0

for (const lang of languages) {
    const poFile = join(djangoLocalePath, lang, "LC_MESSAGES", "djangojs.po")
    if (!existsSync(poFile)) continue

    const poContent = readFileSync(poFile, "utf8")
    const translationMap = new Map()

    let currentMsgid = null
    let currentComment = ""
    for (const line of poContent.split("\n")) {
        const trimmed = line.trim()
        if (trimmed.startsWith("#:")) {
            if (currentMsgid === null) currentComment += line + "\n"
            continue
        }
        if (trimmed.startsWith("#,") || trimmed.startsWith("#.") || trimmed.startsWith("#|")) {
            if (currentMsgid === null) currentComment += line + "\n"
            continue
        }
        if (trimmed.startsWith("#") && !trimmed.startsWith("#:")) continue
        if (trimmed.startsWith('msgid "')) {
            currentMsgid = unescapePo(trimmed.slice(7, -1))
            continue
        }
        if (trimmed.startsWith('msgid ')) {
            currentMsgid = unescapePo(trimmed.slice(6))
            continue
        }
        if (trimmed.startsWith('msgstr "') && currentMsgid !== null) {
            const msgstr = unescapePo(trimmed.slice(8, -1))
            if (msgstr) translationMap.set(currentMsgid, { msgstr, comment: currentComment.trim() })
            currentMsgid = null
            currentComment = ""
            continue
        }
        if (trimmed.startsWith('msgstr ') && currentMsgid !== null) {
            const msgstr = unescapePo(trimmed.slice(7))
            if (msgstr) translationMap.set(currentMsgid, { msgstr, comment: currentComment.trim() })
            currentMsgid = null
            currentComment = ""
            continue
        }
        if (trimmed.startsWith('msgid_plural') || trimmed.startsWith('msgstr[')) {
            currentMsgid = null
            currentComment = ""
            continue
        }
        if (trimmed.startsWith('"') && currentMsgid !== null) {
            currentMsgid += unescapePo(trimmed.slice(1, -1))
        }
    }

    const entries = []
    for (const msgid of msgids) {
        const translation = translationMap.get(msgid)
        const msgstr = translation ? translation.msgstr : ""
        const comment = translation ? translation.comment : ""
        entries.push({ msgid, msgstr, comment })
        if (msgstr) totalTranslated++
    }
    entries.sort((a, b) => a.msgid.localeCompare(b.msgid))

    const header = [
        "# Translations for @fiduswriter/document",
        `# Language: ${lang}`,
        "# Auto-generated by extract-i18n.js",
        "#",
        'msgid ""',
        'msgstr ""',
        '"Content-Type: text/plain; charset=UTF-8\\n"',
        `"Language: ${lang}\\n"`,
        '"Plural-Forms: nplurals=2; plural=(n != 1);\\n"',
        "",
    ].join("\n")

    const body = entries
        .map((e) => {
            let lines = ""
            if (e.comment) lines += e.comment + "\n"
            lines += `msgid "${escapePo(e.msgid)}"\n`
            lines += `msgstr "${escapePo(e.msgstr)}"\n`
            return lines + "\n"
        })
        .join("")

    const langDir = join(root, "locale", lang, "LC_MESSAGES")
    mkdirSync(langDir, { recursive: true })
    writeFileSync(join(langDir, "messages.po"), header + body, "utf8")

    const translated = entries.filter((e) => e.msgstr).length
    console.log(`  ${lang}: ${entries.length} entries, ${translated} translated`)
}

console.log(`\nTotal translated: ${totalTranslated}`)

function escapePo(s) {
    return s.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\n/g, "\\n").replace(/\r/g, "\\r").replace(/\t/g, "\\t")
}
function unescapePo(s) {
    return s.replace(/\\"/g, '"').replace(/\\n/g, "\n").replace(/\\r/g, "\r").replace(/\t/g, "\t").replace(/\\\\/g, "\\")
}
